/**
 * Runtime configuration
 * This file can be generated by docker-entrypoint.sh at container startup
 * or use build-time defaults
 */

// Runtime config values - will be replaced by docker-entrypoint.sh if running in Docker
// Otherwise falls back to build-time VITE_* environment variables
export const RUNTIME_CONFIG = {
  ARK_SERVER: undefined as string | undefined,
  MAX_PERCENTAGE: undefined as number | undefined,
  SENTRY_DSN: undefined as string | undefined,
  BOLTZ_URL: undefined as string | undefined,
}

/**
 * Get a config value with fallback to build-time env var
 */
export function getConfig<T = string>(
  key: keyof typeof RUNTIME_CONFIG,
  envVarName: string,
  defaultValue?: T,
): T | string | undefined {
  const runtimeValue = RUNTIME_CONFIG[key]
  if (runtimeValue !== undefined && runtimeValue !== null && runtimeValue !== '') {
    return runtimeValue as T
  }

  // Fallback to build-time env var
  const envValue = (import.meta.env as Record<string, string>)[envVarName]
  if (envValue !== undefined) {
    return envValue as T
  }

  return defaultValue
}
