#!/usr/bin/env node

/**
 * Generate VAPID keys for Web Push and create .dev.vars for local testing
 * Run: npm run generate-vapid
 */

const webpush = require('web-push');
const fs = require('fs');
const path = require('path');

console.log('Generating VAPID keys for Web Push...\n');

const vapidKeys = webpush.generateVAPIDKeys();

console.log('Public Key:');
console.log(vapidKeys.publicKey);
console.log('\nPrivate Key:');
console.log(vapidKeys.privateKey);

// Create .dev.vars file for local testing
const devVarsPath = path.join(__dirname, '..', '.dev.vars');
const devVarsContent = `# Local development environment variables
# Auto-generated by generate-vapid.js
VAPID_PUBLIC_KEY=${vapidKeys.publicKey}
VAPID_PRIVATE_KEY=${vapidKeys.privateKey}
VAPID_SUBJECT=https://arkade.money
API_KEY=change-me-to-a-secure-api-key
`;

try {
  fs.writeFileSync(devVarsPath, devVarsContent);
  console.log('\n✅ Created .dev.vars file for local testing');
  console.log(`   Location: ${devVarsPath}`);
} catch (error) {
  console.error('\n❌ Failed to create .dev.vars:', error.message);
}

console.log('\n📝 For local testing:');
console.log('   npm run dev');
console.log('   The push service will use the keys from .dev.vars');

console.log('\n🚀 For production deployment:');
console.log('   wrangler secret put VAPID_PUBLIC_KEY');
console.log('   wrangler secret put VAPID_PRIVATE_KEY');
console.log('   wrangler secret put VAPID_SUBJECT');
console.log('   wrangler secret put API_KEY');
console.log('\n💡 VAPID_SUBJECT should be a mailto: or https: URL');
console.log('   Example: mailto:support@arkade.money');
