#!/usr/bin/env python3
"""Generate gitignored subflows with secrets from maestro/config.yaml.

Maestro Studio does not reliably resolve ${WALLET_NSEC} / ${WALLET_PASSWORD}
from CLI -e or MAESTRO_* shell exports. This script materialises them into
local subflows before studio.sh / run.sh / run-scenario.sh run.
"""

from __future__ import annotations

import re
import sys
from pathlib import Path

MAESTRO_DIR = Path(__file__).resolve().parents[1]
CONFIG = MAESTRO_DIR / "config.yaml"
SUBFLOWS = MAESTRO_DIR / "complete-tests" / "subflows"

ENV_RE = re.compile(r'^  ([A-Z_]+): *"(.*)"\s*$')


def read_config_env(path: Path) -> dict[str, str]:
    if not path.is_file():
        sys.exit(f"error: missing {path} — cp config.yaml.example config.yaml")
    env: dict[str, str] = {}
    in_env = False
    for line in path.read_text().splitlines():
        if line.strip() == "env:":
            in_env = True
            continue
        if in_env:
            if line and not line.startswith("  "):
                break
            m = ENV_RE.match(line)
            if m:
                key, value = m.groups()
                env[key] = unescape_yaml_double_quoted(value)
    return env


def unescape_yaml_double_quoted(value: str) -> str:
    # Inverse of yaml_double_quoted: backslashes first, then quotes.
    return value.replace("\\\\", "\\").replace('\\"', '"')


def yaml_double_quoted(value: str) -> str:
    return '"' + value.replace("\\", "\\\\").replace('"', '\\"') + '"'


def write_input_subflow(path: Path, secret: str, label: str) -> None:
    path.write_text(
        "\n".join(
            [
                "appId: com.android.chrome",
                "---",
                "# AUTO-GENERATED by sync-secret-subflows.py — do not edit",
                f"# {label} from config.yaml (gitignored)",
                "- inputText:",
                f"    text: {yaml_double_quoted(secret)}",
                "",
            ]
        )
    )


def main() -> None:
    env = read_config_env(CONFIG)
    nsec = env.get("WALLET_NSEC", "")
    password = env.get("WALLET_PASSWORD", "")

    if not nsec or nsec == "nsec1your-test-restore-key-here":
        sys.exit("error: set WALLET_NSEC in maestro/config.yaml")

    SUBFLOWS.mkdir(parents=True, exist_ok=True)
    write_input_subflow(SUBFLOWS / "_input_wallet_nsec.yaml", nsec, "WALLET_NSEC")
    write_input_subflow(
        SUBFLOWS / "_input_wallet_password.yaml",
        password,
        "WALLET_PASSWORD",
    )
    print(f"synced secret subflows → {SUBFLOWS}/_input_wallet_*.yaml")


if __name__ == "__main__":
    main()
